function [idx, te] = liveSpectrumPointSolve(spec, wavelength, height, ...
        n_substrate, n_pillar, n_background, n_cap, theta, period, ...
        p1, p2, h_cap, pol, nn, idx)
% LIVESPECTRUMPOINTSOLVE  One-wavelength RCWA solve for parfeval workers.

    [~, ~, te, ~] = RCWA_solve(spec, wavelength, height, n_substrate, ...
        n_pillar, n_background, n_cap, theta, period, p1, p2, h_cap, pol, nn);
end
