function spec = shape_registry(shape_name)
% SHAPE_REGISTRY  Return the specification struct for a named pillar shape.
%
%   spec       = shape_registry(shape_name)
%   shape_list = shape_registry()          % returns cell array of valid names
%
%   This is the single file that defines every shape in the library.
%   The rest of the pipeline (solver, writer, reader, table builder, GUI)
%   consult this spec and never contain shape-specific logic themselves.
%
% -----------------------------------------------------------------------
%   SPEC FIELDS
% -----------------------------------------------------------------------
%   .shape_name      string   Internal name, used for folder naming and .mat
%                             storage (e.g. 'cross_with_cap').
%   .display_name    string   Human-readable label for the GUI dropdown.
%   .build_fn        fhandle  Geometry builder. Unified call signature:
%                               [tex, prof] = build_fn(n_bg, n_pil, n_cap,
%                                               n_sub, p1, p2, h_cap, height)
%                             p2 is ignored (~) for 1-parameter shapes.
%   .n_geom_params   integer  1 or 2 free geometric parameters.
%   .param1_name     string   Name stored in the .mat Param array ('diameter').
%   .param1_label    string   Label shown in the GUI and used in row names.
%   .param2_name     string   Empty string for 1-parameter shapes.
%   .param2_label    string   Empty string for 1-parameter shapes.
%   .row_name_fn     fhandle  Generates the filter-table row name:
%                               name = row_name_fn(height, pitch, p1, p2)
%   .shape_tag       string   Short tag used in CSV/plot titles ('Circle').
%
% -----------------------------------------------------------------------
%   GEOMETRY BUILDER CONVENTION
% -----------------------------------------------------------------------
%   All builders share the same call signature:
%       [textures, profile] = build_fn(n_bg, n_pil, n_cap, n_sub,
%                                       p1, p2, h_cap, height)
%
%   Parameter semantics by shape:
%       Circle  : p1 = diameter,       p2 = unused (~)
%       Square  : p1 = width,          p2 = unused (~)
%       Cross   : p1 = major width,    p2 = aspect ratio  (w2 = p1 * p2)
%       Ellipse : p1 = major diameter, p2 = aspect ratio  (minor = p1 * p2)
%
% -----------------------------------------------------------------------
%   HOW TO ADD A NEW SHAPE
% -----------------------------------------------------------------------
%   1. Write  build_<shape>.m  with the unified signature above.
%      See build_circle_with_cap.m for a minimal example.
%   2. Add a 'case' block below following the exact same pattern.
%   3. Nothing else in the pipeline needs to change.
%
% -----------------------------------------------------------------------

    if nargin == 0
        % Return list of all registered shape names.
        spec = { ...
            'circle_with_cap', ...
            'tapered_circle_with_cap', ...
            'square_with_cap', ...
            'cross_with_cap',  ...
            'tapered_cross_with_cap', ...
            'ellipse_with_cap' ...
        };
        return;
    end

    switch lower(strtrim(shape_name))

        % -----------------------------------------------------------------
        case 'circle_with_cap'
            spec = make_spec( ...
                'circle_with_cap', ...
                'Circle (with cap)', ...
                @build_circle_with_cap, ...
                1, ...
                'diameter', 'Diameter (um)', ...
                '',         '', ...
                @(h,p,p1,~) sprintf( ...
                    'Height_%04.2f_Pitch_%.3f_Diameter_%.3f_Circle', h, p, p1), ...
                'Circle');

        % -----------------------------------------------------------------
        case 'tapered_circle_with_cap'
            spec = make_spec( ...
                'tapered_circle_with_cap', ...
                'Tapered Circle (with cap)', ...
                @build_tapered_circle_with_cap, ...
                1, ...
                'diameter', 'Top Diameter (um)', ...
                '',         '', ...
                @(h,p,p1,~) tapered_circle_row_name(h, p, p1), ...
                'TaperedCircle');
            spec.build_options = struct( ...
                'taper_mid_delta', 0, ...
                'taper_bottom_delta', 0, ...
                'taper_num_slices', 6);

        % -----------------------------------------------------------------
        case 'square_with_cap'
            spec = make_spec( ...
                'square_with_cap', ...
                'Square (with cap)', ...
                @build_square_with_cap, ...
                1, ...
                'width', 'Width (um)', ...
                '',      '', ...
                @(h,p,p1,~) sprintf( ...
                    'Height_%04.2f_Pitch_%.3f_Width_%.3f_Square', h, p, p1), ...
                'Square');

        % -----------------------------------------------------------------
        case 'cross_with_cap'
            spec = make_spec( ...
                'cross_with_cap', ...
                'Cross (with cap)', ...
                @build_cross_with_cap, ...
                2, ...
                'width',        'Major Width (um)', ...
                'aspect_ratio', 'Aspect Ratio (w2/w1)', ...
                @(h,p,p1,p2) sprintf( ...
                    'Height_%04.2f_Pitch_%.3f_Width_%.3f_AR_%.2f_Cross', h, p, p1, p2), ...
                'Cross');

        % -----------------------------------------------------------------
        case 'tapered_cross_with_cap'
            spec = make_spec( ...
                'tapered_cross_with_cap', ...
                'Tapered Cross (with cap)', ...
                @build_tapered_cross_with_cap, ...
                2, ...
                'width',        'Top Major Width (um)', ...
                'aspect_ratio', 'Aspect Ratio (w2/w1)', ...
                @(h,p,p1,p2) tapered_cross_row_name(h, p, p1, p2), ...
                'TaperedCross');
            spec.build_options = struct( ...
                'taper_mid_delta', 0, ...
                'taper_bottom_delta', 0, ...
                'taper_num_slices', 6);

        % -----------------------------------------------------------------
        case 'ellipse_with_cap'
            spec = make_spec( ...
                'ellipse_with_cap', ...
                'Ellipse (with cap)', ...
                @build_ellipse_with_cap, ...
                2, ...
                'major_diameter', 'Major Diameter (um)', ...
                'aspect_ratio',   'Aspect Ratio (minor/major)', ...
                @(h,p,p1,p2) sprintf( ...
                    'Height_%04.2f_Pitch_%.3f_MajDiam_%.3f_AR_%.2f_Ellipse', h, p, p1, p2), ...
                'Ellipse');

        % -----------------------------------------------------------------
        otherwise
            available = strjoin(shape_registry(), ', ');
            error('shape_registry:unknown', ...
                'Unknown shape: "%s".\nAvailable shapes: %s', ...
                shape_name, available);
    end
end

% =========================================================================
% Internal helper — assembles the spec struct with consistent field names.
% =========================================================================
function s = make_spec(shape_name, display_name, build_fn, n_geom_params, ...
        param1_name, param1_label, param2_name, param2_label, ...
        row_name_fn, shape_tag)

    s.shape_name     = shape_name;
    s.display_name   = display_name;
    s.build_fn       = build_fn;
    s.n_geom_params  = n_geom_params;
    s.param1_name    = param1_name;
    s.param1_label   = param1_label;
    s.param2_name    = param2_name;
    s.param2_label   = param2_label;
    s.row_name_fn    = row_name_fn;
    s.shape_tag      = shape_tag;
end

function name = tapered_cross_row_name(h, p, p1, p2)
    name = sprintf(['Height_%04.2f_Pitch_%.3f_TopWidth_%.3f_' ...
        'AR_%.2f_TaperedCross'], h, p, p1, p2);
end

function name = tapered_circle_row_name(h, p, p1)
    name = sprintf('Height_%04.2f_Pitch_%.3f_TopDiameter_%.3f_TaperedCircle', ...
        h, p, p1);
end
